

export const metadata = {
  title: "MeetReady || Public Profile",
  description: "Generated by create next app",
};

export default function PublicProfileLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
        </body>
    </html>
  );
}
