import DashNav from "@/components/DashNav/DashNav";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
export const metadata = {
  title: "MeetReady || Dashboard",
  description: "Generated by Tech Army",
};

export default async function DashboardLayout({ children }) {

  const session = await getServerSession(authOptions)

  // console.log(session?.user)
  if(!session){
    redirect('/login')
  }
  else if(session?.user?.role === 'jobSeeker'){
    redirect('/Job-Seeker-Dashboard')
  }else if (session?.user?.role === 'newUser'){
    redirect('/roleSetting')
  }
  return (
    <html lang="en" data-theme="light">
      <body className="flex justify-between bg-purple-100 ">
        <DashNav />
        <div className="max-w-7xl mx-auto min-h-screen">{children}</div>
      </body>
    </html>
  );
}
