import DashNav from "@/components/DashNav/DashNav";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "../api/auth/[...nextauth]/route";
import "../globals.css";
export const metadata = {
  title: "MeetReady || Dashboard",
  description: "Generated by Tech Army",
};

export default async function DashboardLayout({ children }) {
  const session = await getServerSession(authOptions);

  // console.log(session?.user)
  if (!session) {
    redirect("/login");
  } else if (session?.user?.role === "jobSeeker") {
    redirect("/Job-Seeker-Dashboard");
  } else if (session?.user?.role === "newUser") {
    redirect("/roleSetting");
  }
  return (
    <html lang="en" data-theme="light">
      <div style={{ display: "flex", flexDirection: "row", height: "100vh" }}>
        <div className="lg:w-72">
          <DashNav />
        </div>
        <div
          style={{
            flex: 1,
            overflowY: "auto",
          }}
          className="md:px-10"
        >
          {/* Content area */}
          {children}
        </div>
      </div>
    </html>
  );
}
