import DashNav from "@/components/DashNav/DashNav";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "../api/auth/[...nextauth]/route";
import "../globals.css";
export const metadata = {
  title: "MeetReady || Dashboard",
  description: "Generated by Tech Army",
};

export default async function DashboardLayout({ children }) {
  const session = await getServerSession(authOptions);

  // console.log(session?.user)
  if (!session) {
    redirect("/login");
  } else if (session?.user?.role === "jobSeeker") {
    redirect("/Job-Seeker-Dashboard");
  } else if (session?.user?.role === "newUser") {
    redirect("/roleSetting");
  }
  return (
    <html lang="en" data-theme="light">
      <body className="flex justify-between bg-gradient-to-r from-[#E7F1FE] via-[#ECF0FE] to-[#F5EEFF] ">
        <DashNav />
        <div className="max-w-7xl mx-auto min-h-screen">{children}</div>
      </body>
    </html>
  );
}
