export const metadata = {
  title: "MeetReady || CreateProfile",
  description: "Generated by create next app",
};

export default function CartLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
