import DashNav from "@/components/JobSeekerDashboard/DashNav/DashNav";
import Layout from "../layout";

export const metadata = {
  title: "MeetReady || CreateProfile",
  description: "Generated by create next app",
};
function layout({ children }) {
  return (
    <Layout withNavbar={false}>
      {children}
    </Layout>
  );
}

export default layout;
