import "../../globals.css";
import DashNav from "@/components/JobSeekerDashboard/DashNav/DashNav";
import JobSeekerDashboardLayout from "../layout";

export const metadata = {
  title: "MeetReady || Dashboard",
  description: "Generated by create next app",
};

export default function CartLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <DashNav />
        </div>
        {children}
      </body>
    </html>
  );
}
