
import Navbar from "@/components/Navbar/Navbar";
import '../../globals.css';
import DashNav from "@/components/DashNav/DashNav";



export const metadata = {
  title: "MeetReady || Cart",
  description: "Generated by create next app",
};

export default function CartLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <div><DashNav/></div>
        {children}
        </body>
    </html>
  );
}
