import "../../globals.css";
import DashNav from "@/components/JobSeekerDashboard/DashNav/DashNav";

export const metadata = {
  title: "MeetReady || Profile",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <div>
            <DashNav />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
