
import Navbar from "@/components/Navbar/Navbar";
import "../globals.css";



export const metadata = {
  title: "MeetReady || Cart",
  description: "Generated by create next app",
};

export default function CartLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <Navbar data-testid="nab" />
        {children}
        </body>
    </html>
  );
}
