import AuthProvider from "@/utils/SessionProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <AuthProvider>
        {children}
        </AuthProvider>

      </body>

        </body>

    </html>
  )
}
