import FBMessenger from "@/components/FBMessenger/FBMessenger"
import { CartProvider } from "@/utils/Cart/CartContext"
import AuthProvider from "@/utils/SessionProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <AuthProvider>
<CartProvider>
        <div>
        {children}
        <FBMessenger/>
        </div>
</CartProvider>
        </AuthProvider>
        </body>
    </html>
  )
}
