import DashNav from '@/components/JobSeekerDashboard/DashNav/DashNav';
import '../globals.css'
import { getServerSession } from 'next-auth';
import { authOptions } from '../api/auth/[...nextauth]/route';
import { redirect } from 'next/navigation';

export const metadata = {
  title: "MeetReady || JobSeekerDashboard",
  description: "Generated by Tech Army",
};

const JobSeekerDashboardLayout = async ({ children }) => {
  const session = await getServerSession(authOptions)

  if(!session){
    redirect('/login')
  }else if(session?.user?.role === 'employer'){
    redirect('/dashboard')
  }else if (session?.user?.role === 'newUser'){
    redirect('/roleSetting')
  }
  return (
    <div className="">
      <div className="max-w-7xl mx-auto min-h-screen">{ children }</div>
    </div>
  )
}

export default JobSeekerDashboardLayout